"""
services/report_generator.py

Generates downloadable executive summary reports as markdown files.
Saved to storage/reports/ for download from the Streamlit UI.
"""

import os
import uuid
from datetime import datetime
from config import REPORTS_DIR


def generate_report(
    file_name: str,
    summary:   dict,
    anomalies: list,
    insights:  str,
    exec_summary: str,
) -> dict:
    """
    Build a markdown report and save to disk.

    Parameters
    ----------
    file_name    : original uploaded file name
    summary      : statistical summary from processor.py
    anomalies    : list of detected anomalies
    insights     : AI generated insights string
    exec_summary : AI generated executive summary string

    Returns
    -------
    dict with report_id and file_path
    """
    report_id = str(uuid.uuid4())[:8]
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    file_path = os.path.join(REPORTS_DIR, f"{report_id}_report.md")

    content = _build_markdown(
        file_name    = file_name,
        summary      = summary,
        anomalies    = anomalies,
        insights     = insights,
        exec_summary = exec_summary,
        timestamp    = timestamp,
    )

    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)

    return {
        "report_id": report_id,
        "file_path": file_path,
        "timestamp": timestamp,
    }


def _build_markdown(
    file_name:    str,
    summary:      dict,
    anomalies:    list,
    insights:     str,
    exec_summary: str,
    timestamp:    str,
) -> str:
    """Build the full markdown report content."""

    lines = []

    # Header
    lines.append(f"# Business Intelligence Report")
    lines.append(f"**File:** {file_name}")
    lines.append(f"**Generated:** {timestamp}")
    lines.append(f"**Sheet:** {summary.get('sheet_name', 'N/A')}")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Executive Summary
    lines.append("## Executive Summary")
    lines.append(exec_summary or "Not generated.")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Dataset Overview
    lines.append("## Dataset Overview")
    lines.append(f"- **Total Rows:** {summary.get('total_rows', 0):,}")
    lines.append(f"- **Total Columns:** {summary.get('total_columns', 0)}")
    lines.append(f"- **Columns:** {', '.join(summary.get('columns', []))}")
    lines.append("")

    # Numeric Stats
    numeric_stats = summary.get("numeric_stats", {})
    if numeric_stats:
        lines.append("## Numeric Column Statistics")
        lines.append("| Column | Min | Max | Mean | Median | Sum |")
        lines.append("|--------|-----|-----|------|--------|-----|")
        for col, stats in numeric_stats.items():
            lines.append(
                f"| {col} | {stats['min']:,} | {stats['max']:,} | "
                f"{stats['mean']:,} | {stats['median']:,} | {stats['sum']:,} |"
            )
        lines.append("")

    # Categorical Stats
    cat_stats = summary.get("categorical_stats", {})
    if cat_stats:
        lines.append("## Categorical Column Statistics")
        for col, stats in cat_stats.items():
            lines.append(f"### {col}")
            lines.append(f"- Unique values: {stats['unique_count']:,}")
            lines.append(f"- Most common: {stats['most_common']}")
            top5 = ", ".join(f"{k} ({v})" for k, v in list(stats["top_5"].items())[:5])
            lines.append(f"- Top values: {top5}")
        lines.append("")

    # Anomalies
    lines.append("## Data Quality & Anomalies")
    if anomalies:
        lines.append(f"**{len(anomalies)} anomalies detected:**")
        lines.append("")
        for a in anomalies:
            severity_emoji = {"high": "🔴", "medium": "🟡", "low": "🟢"}.get(
                a["severity"], "⚪"
            )
            lines.append(f"{severity_emoji} **{a['type'].replace('_', ' ').title()}** "
                         f"— {a['detail']}")
        lines.append("")
    else:
        lines.append("✅ No anomalies detected.")
        lines.append("")

    # AI Insights
    lines.append("## AI Generated Insights")
    lines.append(insights or "Not generated.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("*Report generated by AI Business Report Analyzer v2*")

    return "\n".join(lines)