import { useState, useEffect } from "react";
import { dataApi } from "../../api/client";
import FileSelector from "../../components/data/FileSelector";

export default function DataQueryLog({ activeFileId, onFileSelect }) {
  const [fileId, setFileId] = useState(activeFileId || "");
  const [logs, setLogs] = useState([]);
  const [summary, setSummary] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [expanded, setExpanded] = useState(null); // index of expanded SQL row
  const [viewMode, setViewMode] = useState("file"); // "file" | "all"

  useEffect(() => {
    if (activeFileId) setFileId(activeFileId);
  }, [activeFileId]);

  useEffect(() => {
    if (viewMode === "all") loadAll();
    else if (fileId) loadForFile(fileId);
  }, [fileId, viewMode]);

  const loadForFile = async (id) => {
    if (!id) return;
    setLoading(true);
    setError("");
    try {
      const [logsRes, summRes] = await Promise.all([
        dataApi.getQueryLogByFile(id),
        dataApi.getQueryLogSummary(),
      ]);
      setLogs(logsRes.data?.logs || logsRes.data || []);
      setSummary(summRes.data);
    } catch (e) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  };

  const loadAll = async () => {
    setLoading(true);
    setError("");
    try {
      const [logsRes, summRes] = await Promise.all([
        dataApi.getQueryLog(),
        dataApi.getQueryLogSummary(),
      ]);
      setLogs(logsRes.data?.logs || logsRes.data || []);
      setSummary(summRes.data);
    } catch (e) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  };

  const handleSelectFile = (id) => {
    setFileId(id);
    setLogs([]);
    setViewMode("file");
    if (onFileSelect) onFileSelect(id);
  };

  const clearAll = async () => {
    if (!window.confirm("Clear all query logs?")) return;
    await dataApi.clearQueryLog().catch(() => {});
    setLogs([]);
    setSummary(null);
  };

  const statusBadge = (s) => {
    if (!s) return <span className="text-muted text-sm">—</span>;
    const map = {
      success: "badge-success",
      error:   "badge-danger",
      not_sql: "badge-warning",
    };
    return <span className={`badge ${map[s] || "badge-neutral"}`}>{s}</span>;
  };

  return (
    <div className="page-content">
      <div className="page-inner">
        <div className="page-header">
          <div className="page-header-left">
            <h1>Query Log</h1>
            <p>All SQL queries generated by the BI pipeline</p>
          </div>
          <div className="page-header-actions">
            {/* View mode toggle */}
            <div className="mode-toggle">
              <button
                className={`mode-btn${viewMode === "file" ? " active" : ""}`}
                onClick={() => setViewMode("file")}
              >
                By File
              </button>
              <button
                className={`mode-btn${viewMode === "all" ? " active" : ""}`}
                onClick={() => setViewMode("all")}
              >
                All Logs
              </button>
            </div>
            {viewMode === "file" && (
              <FileSelector selectedId={fileId} onSelect={handleSelectFile} />
            )}
            <button
              className="btn btn-secondary btn-sm"
              onClick={() => viewMode === "all" ? loadAll() : loadForFile(fileId)}
            >
              Refresh
            </button>
            {logs.length > 0 && (
              <button className="btn btn-danger btn-sm" onClick={clearAll}>
                Clear All
              </button>
            )}
          </div>
        </div>

        {error && <div className="error-banner mb-16">{error}</div>}

        {/* Summary KPIs */}
        {summary && (
          <div className="kpi-grid mb-24">
            <div className="kpi-card">
              <div className="kpi-label">Total Queries</div>
              <div className="kpi-value">{summary.total ?? logs.length}</div>
            </div>
            <div className="kpi-card">
              <div className="kpi-label">Successful</div>
              <div className="kpi-value" style={{ color: "var(--success)" }}>
                {summary.success ?? "—"}
              </div>
            </div>
            <div className="kpi-card">
              <div className="kpi-label">Errors</div>
              <div className="kpi-value" style={{ color: summary.errors > 0 ? "var(--danger)" : "var(--text-primary)" }}>
                {summary.errors ?? "—"}
              </div>
            </div>
            <div className="kpi-card">
              <div className="kpi-label">Non-SQL</div>
              <div className="kpi-value" style={{ color: "var(--warning)" }}>
                {summary.not_sql ?? "—"}
              </div>
            </div>
          </div>
        )}

        {viewMode === "file" && !fileId ? (
          <div className="empty-state">
            <div className="empty-state-title">No file selected</div>
            <p>Select a file to view its query log, or switch to "All Logs".</p>
          </div>
        ) : loading ? (
          <div className="empty-state">
            <div className="spinner" style={{ margin: "0 auto" }} />
          </div>
        ) : logs.length === 0 ? (
          <div className="empty-state">
            <div className="empty-state-title">No queries logged yet</div>
            <p>Ask questions in Data Chat to generate SQL queries.</p>
          </div>
        ) : (
          <>
            <div className="table-wrap">
              <table>
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Question</th>
                    <th>Status</th>
                    <th>SQL</th>
                    <th>Answer Preview</th>
                    <th>Timestamp</th>
                  </tr>
                </thead>
                <tbody>
                  {logs.map((log, i) => (
                    <>
                      <tr
                        key={i}
                        style={{ cursor: log.sql ? "pointer" : "default" }}
                        onClick={() => log.sql && setExpanded(expanded === i ? null : i)}
                      >
                        <td className="text-mono text-sm text-muted">
                          {String(i + 1).padStart(2, "0")}
                        </td>
                        <td style={{ maxWidth: 260 }}>
                          <div
                            className="truncate"
                            style={{ fontWeight: 500, color: "var(--text-primary)" }}
                            title={log.query || log.question}
                          >
                            {log.query || log.question || "—"}
                          </div>
                          {log.file_id && viewMode === "all" && (
                            <div className="text-mono text-sm text-muted truncate">{log.file_id}</div>
                          )}
                        </td>
                        <td>{statusBadge(log.status)}</td>
                        <td>
                          {log.sql ? (
                            <span
                              style={{
                                fontFamily: "var(--font-mono)",
                                fontSize: 11,
                                color: "#ccc",
                                cursor: "pointer",
                              }}
                              title="Click row to expand SQL"
                            >
                              {expanded === i ? "▼ Hide" : "▶ Show"}
                            </span>
                          ) : (
                            <span className="text-muted text-sm">—</span>
                          )}
                        </td>
                        <td style={{ maxWidth: 280 }}>
                          <div className="truncate text-sm" title={log.answer}>
                            {log.answer || "—"}
                          </div>
                        </td>
                        <td className="text-sm text-muted" style={{ whiteSpace: "nowrap" }}>
                          {log.timestamp || log.created_at
                            ? new Date(log.timestamp || log.created_at).toLocaleString(undefined, {
                                month: "short", day: "numeric",
                                hour: "2-digit", minute: "2-digit",
                              })
                            : "—"}
                        </td>
                      </tr>
                      {expanded === i && log.sql && (
                        <tr key={`sql-${i}`}>
                          <td colSpan={6} style={{ padding: "0 16px 14px" }}>
                            <pre style={{
                              background: "var(--bg-elevated)",
                              border: "1px solid var(--border)",
                              borderRadius: "var(--radius)",
                              padding: "12px 16px",
                              fontFamily: "var(--font-mono)",
                              fontSize: 12,
                              color: "var(--info)",
                              overflowX: "auto",
                              margin: 0,
                              lineHeight: 1.6,
                            }}>
                              {log.sql}
                            </pre>
                          </td>
                        </tr>
                      )}
                    </>
                  ))}
                </tbody>
              </table>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
