import { useState, useEffect } from "react";
import { dataApi } from "../../api/client";
import FileSelector from "../../components/data/FileSelector";

export default function DataQueryLog({ activeFileId, onFileSelect }) {
  const [fileId, setFileId] = useState(activeFileId || "");
  const [logs, setLogs] = useState([]);
  const [summary, setSummary] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [fileOnly, setFileOnly] = useState(false);
  const [expandedSql, setExpandedSql] = useState({});

  useEffect(() => { if (activeFileId) setFileId(activeFileId); }, [activeFileId]);
  useEffect(() => { load(); }, [fileOnly, fileId]);
  useEffect(() => { load(); }, [fileOnly, fileId]);

  const load = async () => {
    setLoading(true);
    setError("");
    try {
      const [logsRes, summRes] = await Promise.all([
        fileOnly && fileId
          ? dataApi.getQueryLogByFile(fileId)
          : dataApi.getQueryLog(),
        dataApi.getQueryLogSummary(),
      ]);
      setLogs(logsRes.data?.logs || logsRes.data || []);
      setSummary(summRes.data);
    } catch (e) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  };

  // No window.confirm
  const clearAll = async () => {
    await dataApi.clearQueryLog().catch(() => { });
    setLogs([]);
    setSummary(null);
  };

  const handleSelectFile = (id) => {
    setFileId(id);
    if (onFileSelect) onFileSelect(id);
  };

  const toggleSql = (i) =>
    setExpandedSql((prev) => ({ ...prev, [i]: !prev[i] }));

  const statusBadge = (s) => {
    const map = { success: "badge-success", error: "badge-danger", not_sql: "badge-warning" };
    return <span className={`badge ${map[s] || "badge-neutral"}`}>{s || "—"}</span>;
  };

  return (
    <div className="page-content">
      <div className="page-inner">
        <div className="page-header">
          <div className="page-header-left">
            <h1>Query Log</h1>
            <p>All SQL queries generated by the BI pipeline</p>
          </div>
          <div className="page-header-actions">
            <label style={{ display: "flex", alignItems: "center", gap: 8, fontSize: 13, cursor: "pointer", color: "var(--text-secondary)" }}>
              <input
                type="checkbox"
                checked={fileOnly}
                onChange={(e) => setFileOnly(e.target.checked)}
                style={{ accentColor: "var(--brand-primary)" }}
              />
              Show current file only
            </label>
            {fileOnly && <FileSelector selectedId={fileId} onSelect={handleSelectFile} />}
            <button className="btn btn-secondary btn-sm" onClick={load}>Refresh</button>
            {logs.length > 0 && (
              <button className="btn btn-danger btn-sm" onClick={clearAll}>Clear All</button>
            )}
          </div>
        </div>

        {error && <div className="error-banner mb-16">{error}</div>}

        {/* KPI row */}
        {summary && (
          <div className="kpi-grid mb-24">
            {[
              { label: "Total Queries", value: summary.total ?? logs.length },
              { label: "Successful", value: summary.success ?? "—", color: "var(--success)" },
              { label: "Errors", value: summary.errors ?? "—", color: (summary.errors || 0) > 0 ? "var(--danger)" : undefined },
              { label: "Non-SQL", value: summary.not_sql ?? "—", color: "var(--warning)" },
            ].map((k) => (
              <div key={k.label} className="kpi-card">
                <div className="kpi-label">{k.label}</div>
                <div className="kpi-value" style={{ color: k.color || "var(--text-primary)" }}>{k.value}</div>
              </div>
            ))}
          </div>
        )}

        {loading ? (
          <div className="empty-state"><div className="spinner" style={{ margin: "0 auto" }} /></div>
        ) : logs.length === 0 ? (
          <div className="empty-state">
            <div className="empty-state-title">No queries logged yet</div>
            <p>Ask questions in Data Chat to generate SQL queries.</p>
          </div>
        ) : (
          <div className="table-wrap">
            <table>
              <thead>
                <tr>
                  <th>#</th>
                  <th>Question</th>
                  <th>SQL</th>
                  <th>Status</th>
                  <th>Rows</th>
                  <th>Timestamp</th>
                </tr>
              </thead>
              <tbody>
                {logs.map((log, i) => (
                  <>
                    <tr key={i}>
                      <td className="text-mono text-sm text-muted">{String(i + 1).padStart(2, "0")}</td>
<td style={{ width: 200, maxWidth: 200, overflow: "hidden" }}>
  <div style={{ color: "var(--text-primary)", fontSize: 13, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }} title={log.question || log.query}>
    {log.question || log.query || "—"}
  </div>
                        {!fileOnly && log.file_name && (
                          <div className="text-sm text-muted">{log.file_name}</div>
                        )}
                      </td>
                      <td>
                        {log.sql ? (
                          <button
                            type="button"
                            onClick={() => toggleSql(i)}
                            style={{ background: "none", border: "none", cursor: "pointer", fontSize: 11, color: "var(--info)", fontFamily: "var(--font-mono)", padding: 0 }}
                          >
                            {expandedSql[i] ? "▼ Hide" : "▶ " + log.sql.slice(0, 60) + (log.sql.length > 60 ? "…" : "")}
                          </button>
                        ) : (
                          <span className="text-muted text-sm">—</span>
                        )}
                      </td>
                      <td>{statusBadge(log.status)}</td>
                      <td className="text-mono text-sm">{log.result_rows ?? log.row_count ?? log.rows ?? "—"}</td>
                      <td className="text-sm text-muted" style={{ whiteSpace: "nowrap" }}>
                        {log.asked_at || log.timestamp
                          ? new Date(log.asked_at || log.timestamp).toLocaleString(undefined, { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" })
                          : "—"}
                      </td>
                    </tr>
                    {expandedSql[i] && log.sql && (
                      <tr key={`sql-${i}`}>
                        <td colSpan={6} style={{ padding: "0 16px 14px" }}>
                          <pre style={{ background: "var(--bg-elevated)", border: "1px solid var(--border)", borderRadius: "var(--radius)", padding: "12px 16px", fontFamily: "var(--font-mono)", fontSize: 12, color: "var(--info)", overflowX: "auto", margin: 0, lineHeight: 1.6 }}>
                            {log.sql}
                          </pre>
                        </td>
                      </tr>
                    )}
                  </>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}